services:
  - type: web
    name: itinerary-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.12
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
